// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeYOaqrsERZqcCeR1lhdVt3TkCNaVOqyA',
    appId: '1:592880124586:web:7d8a4cfde05f0761c4c6d3',
    messagingSenderId: '592880124586',
    projectId: 'eventec-3bf83',
    authDomain: 'eventec-3bf83.firebaseapp.com',
    storageBucket: 'eventec-3bf83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjY79DwRan7_Xt6K0evLEj303FkQS8lSg',
    appId: '1:592880124586:android:75b6b799d082bba6c4c6d3',
    messagingSenderId: '592880124586',
    projectId: 'eventec-3bf83',
    storageBucket: 'eventec-3bf83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDjZpBqdxiBKYcgWtjxk-bSJ8XR-IS3g0',
    appId: '1:592880124586:ios:4ac78fe42f6ddeb3c4c6d3',
    messagingSenderId: '592880124586',
    projectId: 'eventec-3bf83',
    storageBucket: 'eventec-3bf83.appspot.com',
    iosBundleId: 'com.example.eventecFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDjZpBqdxiBKYcgWtjxk-bSJ8XR-IS3g0',
    appId: '1:592880124586:ios:38eebdc24a39d185c4c6d3',
    messagingSenderId: '592880124586',
    projectId: 'eventec-3bf83',
    storageBucket: 'eventec-3bf83.appspot.com',
    iosBundleId: 'com.example.eventecFirebase.RunnerTests',
  );
}
