// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHzVpYo_ovT6cC9GfGB8l0pzMg_sSeG9M',
    appId: '1:207072574847:web:11970c6e96daa4450d2e4a',
    messagingSenderId: '207072574847',
    projectId: 'eventec-firebase',
    authDomain: 'eventec-firebase.firebaseapp.com',
    storageBucket: 'eventec-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzgtLQpvj8sjcxbQ9p75x0NOAHnloKSLw',
    appId: '1:207072574847:android:21c81cb52ce1c4e90d2e4a',
    messagingSenderId: '207072574847',
    projectId: 'eventec-firebase',
    storageBucket: 'eventec-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8i6bpeOCAwJ-jo62m1vQh6_p0lgtJE-w',
    appId: '1:207072574847:ios:344020660837bf680d2e4a',
    messagingSenderId: '207072574847',
    projectId: 'eventec-firebase',
    storageBucket: 'eventec-firebase.appspot.com',
    iosBundleId: 'com.example.eventecFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8i6bpeOCAwJ-jo62m1vQh6_p0lgtJE-w',
    appId: '1:207072574847:ios:fcd7d4408488bc5f0d2e4a',
    messagingSenderId: '207072574847',
    projectId: 'eventec-firebase',
    storageBucket: 'eventec-firebase.appspot.com',
    iosBundleId: 'com.example.eventecFirebase.RunnerTests',
  );
}
